Algoritmo "Valor do carro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaja
// Descrição   : Fazer a cotação de um carro com as porcentagens dos impostos.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/03/2023
Var
// Seção de Declarações das variáveis 
custoFA: real

Inicio
escreva ("Valor de Fabrica: ")
leia (custoFA)
escreva("Custo Final com imposto e taxas: ", custoFA+(custoFA * 0.28)+(custoFA*0.45))


Fimalgoritmo